title: Enterprise Reporting System
email: your-email@example.com
description: >-
  Comprehensive documentation for the Enterprise Reporting System - 
  a monitoring and analytics platform for enterprise environments.
baseurl: "/enterprise-reporting" # the subpath of your site, e.g. /blog
url: "https://your-org.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: your_username
github_username: your_username

# Build settings
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Just the Docs configuration
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2

# Footer content
footer_content: "Distributed by an <a href=\"https://github.com/your-org/enterprise-reporting/blob/main/LICENSE\">Apache 2.0 License</a>."

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Enterprise Reporting on GitHub":
    - "//github.com/your-org/enterprise-reporting"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# External navigation links
# By default, external links will open in a new tab.
# Add the external_nav_exclude property to disable this behavior
# external_nav_exclude: true

# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to quickly copy a link to a section on the page.
heading_anchors: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/your-org/enterprise-reporting" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately